# Site settings
description: Jus another blog, a classic sysadmin mutating on a devop
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pulpo.github.io" # the base hostname & protocol for your site , estaba en 3000

# User settings
username: Open Bits
user_description: A Sysadmin on the path to Devop
user_title: Linux/Unix System Administration
email: jcaivano@openbits.com.ar
twitter_username: pulpox
github_username:  pulpo
#gplus_username:  lorem_ipsum
disqus_username: pulpox

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
